kind: Ingress
apiVersion: extensions/v1beta1
metadata:
    name: ${PROJECT_NAME}-ingress
    namespace: web
    annotations:
        kubernetes.io/ingress.class: 'nginx'
        certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
spec:
    tls:
        - hosts:
              - www.slugin.io
              - slugin.io
          secretName: web-optoscale-tls
    rules:
        - host: www.slugin.io
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: ${PROJECT_NAME}
                        servicePort: 80
        - host: slugin.io
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: ${PROJECT_NAME}
                        servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
    name: ${PROJECT_NAME}
    namespace: web
spec:
    selector:
        app: ${PROJECT_NAME}
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: ${PROJECT_NAME}
    namespace: web
    labels:
        app: ${PROJECT_NAME}
spec:
    replicas: 2
    selector:
        matchLabels:
            app: ${PROJECT_NAME}
    template:
        metadata:
            labels:
                app: ${PROJECT_NAME}
        spec:
            containers:
                - name: ${PROJECT_NAME}
                  image: eu.gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}:${CIRCLE_SHA1}
                  ports:
                      - name: http
                        containerPort: 80
                        protocol: TCP
